-- CrismaQuest starter saint-card catalogue.
-- Biographies are intentionally short; image assets remain disabled until licence/source review.

INSERT IGNORE INTO cq_saint_cards
(card_number, slug, name, category, short_bio, feast_date, short_teaching, image_path, image_license, active)
VALUES
(1,'sao-carlo-acutis','São Carlo Acutis','Santos Jovens','Jovem italiano que uniu vida cotidiana, amizade, tecnologia e profundo amor à Eucaristia. Seu testemunho mostra que a santidade também pode ser buscada no mundo digital.',NULL,'A Eucaristia, a amizade com Cristo e o uso responsável da tecnologia podem caminhar juntos.',NULL,NULL,1),
(2,'santa-teresinha-menino-jesus','Santa Teresinha do Menino Jesus','Doutores da Igreja','Carmelita conhecida pela pequena via: viver as coisas simples com confiança, amor e entrega a Deus.',NULL,'Grandes caminhos de fé também são construídos em pequenos atos de amor.',NULL,NULL,1),
(3,'sao-francisco-assis','São Francisco de Assis','Fundadores','Escolheu uma vida de simplicidade, fraternidade e serviço, procurando reconhecer em toda a criação um chamado ao louvor.',NULL,'Paz, simplicidade e fraternidade transformam a forma de olhar o mundo e as pessoas.',NULL,NULL,1),
(4,'sao-pedro','São Pedro','Apóstolos','Pescador chamado por Jesus, tornou-se uma das principais testemunhas da comunidade apostólica, aprendendo também por meio das próprias quedas e recomeços.',NULL,'Seguir Cristo inclui aprender, recomeçar e servir à comunidade.',NULL,NULL,1),
(5,'santa-faustina-kowalska','Santa Faustina Kowalska','Místicos','Religiosa polonesa cuja espiritualidade destacou de modo especial a confiança na misericórdia de Deus.',NULL,'A misericórdia cristã conduz à confiança em Deus e ao perdão oferecido ao próximo.',NULL,NULL,1),
(6,'sao-joao-paulo-ii','São João Paulo II','Papas','Papa que marcou gerações pelo anúncio de Cristo, pelo diálogo com os jovens e pela defesa da dignidade de cada pessoa.',NULL,'A fé cristã convida à coragem, à esperança e ao respeito pela dignidade humana.',NULL,NULL,1),
(7,'santa-gianna-beretta-molla','Santa Gianna Beretta Molla','Pais e Mães Santos','Médica, esposa e mãe italiana, recordada por integrar vocação profissional, vida familiar e fé.',NULL,'Trabalho, família e fé podem formar uma única resposta de amor e responsabilidade.',NULL,NULL,1),
(8,'santo-agostinho','Santo Agostinho','Doutores da Igreja','Bispo e pensador cristão cuja longa busca pela verdade passou por dúvidas, mudanças e uma profunda conversão.',NULL,'Buscar a verdade com sinceridade pode abrir espaço para um encontro transformador com Deus.',NULL,NULL,1),
(9,'santa-monica','Santa Mônica','Pais e Mães Santos','Mãe de Santo Agostinho, lembrada por sua perseverança na oração, esperança e cuidado com a família.',NULL,'A perseverança na oração não dispensa a paciência, o cuidado e a esperança.',NULL,NULL,1),
(10,'sao-jose','São José','Santos da Vida de Cristo','Esposo de Maria e pai adotivo de Jesus, é apresentado nos Evangelhos como homem justo, atento e disponível ao chamado de Deus.',NULL,'Servir com discrição, responsabilidade e confiança também é uma forma profunda de missão.',NULL,NULL,1),
(11,'sao-vicente-de-paulo','São Vicente de Paulo','Missionários','Sacerdote francês dedicado ao serviço dos pobres e à organização concreta da caridade cristã.',NULL,'A caridade não é apenas sentimento: ela procura necessidades reais e responde com serviço.',NULL,NULL,1),
(12,'sao-jeronimo','São Jerônimo','Doutores da Igreja','Estudioso das Escrituras que dedicou grande parte da vida à tradução, estudo e transmissão da Palavra de Deus.',NULL,'Conhecer melhor a Escritura ajuda a conhecer melhor Cristo e a história da fé.',NULL,NULL,1),
(13,'santo-inacio-antioquia','Santo Inácio de Antioquia','Mártires','Bispo dos primeiros séculos do cristianismo, deixou cartas importantes sobre unidade, Eucaristia e fidelidade a Cristo.',NULL,'A fé é vivida em comunhão: ninguém percorre sozinho o caminho cristão.',NULL,NULL,1),
(14,'santa-joana-darc','Santa Joana d’Arc','Santos Jovens','Jovem francesa cuja vida ficou marcada por coragem, discernimento, convicção e fidelidade à consciência diante de grandes desafios.',NULL,'Coragem cristã precisa caminhar com discernimento, responsabilidade e consciência bem formada.',NULL,NULL,1),
(15,'sao-john-henry-newman','São John Henry Newman','Doutores da Igreja','Intelectual, pastor e convertido inglês conhecido pela busca paciente da verdade e pelo valor dado à consciência bem formada.',NULL,'Fé e razão não precisam competir: ambas podem participar de uma busca honesta pela verdade.',NULL,NULL,1),
(16,'sao-bento','São Bento','Fundadores','Monge cuja regra organizou uma vida equilibrada de oração, trabalho, comunidade e disciplina.',NULL,'Constância nasce de um ritmo de vida que integra oração, deveres e comunidade.',NULL,NULL,1),
(17,'santos-luis-e-zelia-martin','Santos Luís e Zélia Martin','Pais e Mães Santos','Casal francês e pais de Santa Teresinha, lembrados por viver a fé na família, no trabalho e nas alegrias e dificuldades cotidianas.',NULL,'A vida familiar pode ser lugar concreto de serviço, perdão, cuidado e crescimento na fé.',NULL,NULL,1),
(18,'sao-giuseppe-moscati','São Giuseppe Moscati','Santos Leigos','Médico italiano conhecido por unir competência profissional, atenção aos doentes e vida cristã.',NULL,'Conhecimento e profissão podem ser colocados a serviço da dignidade e do cuidado com o outro.',NULL,NULL,1),
(19,'sao-pio-pietrelcina','São Pio de Pietrelcina','Presbíteros','Frade capuchinho cuja vida foi fortemente associada à oração, ao sacramento da Reconciliação e ao acompanhamento espiritual.',NULL,'Oração, conversão e reconciliação fazem parte de uma caminhada cristã que sempre pode recomeçar.',NULL,NULL,1),
(20,'sao-sebastiao','São Sebastião','Mártires','Cristão dos primeiros séculos venerado como mártir, tradicionalmente associado à firmeza da fé diante da perseguição.',NULL,'Testemunhar a fé exige coerência e perseverança, inclusive quando isso custa alguma coisa.',NULL,NULL,1);

INSERT IGNORE INTO cq_card_editions (card_id, edition_type, visual_asset, chance_weight, active)
SELECT id, 'normal', NULL, 100, 1 FROM cq_saint_cards WHERE card_number BETWEEN 1 AND 20;
