-- CrismaQuest canonical saint-card catalogue.
-- Generated from config/crismaquest/saints.json. Safe and idempotent.

INSERT INTO cq_saint_cards
(card_number, slug, name, category, short_bio, feast_date, short_teaching, image_path, image_license, active)
VALUES
(1,'sao-carlo-acutis','São Carlo Acutis','Santos Jovens','Jovem italiano que uniu vida cotidiana, amizade, tecnologia e profundo amor à Eucaristia. Seu testemunho mostra que a santidade também pode ser buscada no mundo digital.',NULL,'A Eucaristia, a amizade com Cristo e o uso responsável da tecnologia podem caminhar juntos.','https://www.ctsbooks.org/wp-content/uploads/2025/10/St-Carlo-Acutis-Prayer-Card-1.png.webp','Imagem remota indicada pelo administrador',1),
(2,'santa-teresinha-menino-jesus','Santa Teresinha do Menino Jesus','Doutores da Igreja','Carmelita conhecida pela pequena via: viver as coisas simples com confiança, amor e entrega a Deus.','10-01','Pequenos gestos, um grande amor.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Teresa-de-Lisieux.jpg','Domínio público, conforme Wikimedia Commons (PD-US-expired)',1),
(3,'sao-francisco-assis','São Francisco de Assis','Fundadores','Escolheu uma vida de simplicidade, fraternidade e serviço, procurando reconhecer em toda a criação um chamado ao louvor.','10-04','Paz, simplicidade e fraternidade.','/assets/crismaquest/saints/sao-francisco-assis-user.jpg?v=20260911f','Uso autorizado no CrismaQuest pelo administrador',1),
(4,'sao-pedro','São Pedro','Apóstolos','Pescador chamado por Jesus, tornou-se uma das principais testemunhas da comunidade apostólica, aprendendo também por meio das próprias quedas e recomeços.','06-29','Aprender, recomeçar e servir.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Pope-peter%20pprubens.jpg','Domínio público (PD-old-100-expired / PD-Art)',1),
(5,'santa-faustina-kowalska','Santa Faustina Kowalska','Místicos','Religiosa polonesa cuja espiritualidade destacou de modo especial a confiança na misericórdia de Deus.',NULL,'A misericórdia cristã conduz à confiança em Deus e ao perdão oferecido ao próximo.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Faustyna_Kowalska.png','Public domain',1),
(6,'sao-joao-paulo-ii','São João Paulo II','Papas','Papa que marcou gerações pelo anúncio de Cristo, pelo diálogo com os jovens e pela defesa da dignidade de cada pessoa.',NULL,'A fé cristã convida à coragem, à esperança e ao respeito pela dignidade humana.','https://commons.wikimedia.org/wiki/Special:Redirect/file/JohannesPaul2-portrait.jpg','Public domain',1),
(7,'santa-gianna-beretta-molla','Santa Gianna Beretta Molla','Pais e Mães Santos','Médica, esposa e mãe italiana, recordada por integrar vocação profissional, vida familiar e fé.',NULL,'Trabalho, família e fé podem formar uma única resposta de amor e responsabilidade.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Gianna_Beretta_Molla_(cropped).jpg','Public domain',1),
(8,'santo-agostinho','Santo Agostinho','Doutores da Igreja','Bispo e pensador cristão cuja longa busca pela verdade passou por dúvidas, mudanças e uma profunda conversão.',NULL,'Buscar a verdade com sinceridade pode abrir espaço para um encontro transformador com Deus.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Champaigne%2C_Philippe_de_-_Saint_Augustin_-_1645-1650.jpg','Public domain',1),
(9,'santa-monica','Santa Mônica','Pais e Mães Santos','Mãe de Santo Agostinho, lembrada por sua perseverança na oração, esperança e cuidado com a família.',NULL,'A perseverança na oração não dispensa a paciência, o cuidado e a esperança.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Michael%20Willman%20Opus%20Magnum%202019%20P68%20Saint%20Monica%20(1660-1670).jpg','Domínio público (PD-old-100-expired / PD-Art)',1),
(10,'sao-jose','São José','Santos da Vida de Cristo','Esposo de Maria e pai adotivo de Jesus, é apresentado nos Evangelhos como homem justo, atento e disponível ao chamado de Deus.',NULL,'Servir com discrição, responsabilidade e confiança também é uma forma profunda de missão.','/assets/crismaquest/saints/sao-jose-user.jpg?v=20260911f','Uso autorizado no CrismaQuest pelo administrador',1),
(11,'sao-vicente-de-paulo','São Vicente de Paulo','Missionários','Sacerdote francês dedicado ao serviço dos pobres e à organização concreta da caridade cristã.',NULL,'A caridade não é apenas sentimento: ela procura necessidades reais e responde com serviço.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Anonymous_-_Portrait_de_saint_Vincent_de_Paul_(1581-1660)._-_P863_-_Mus%C3%A9e_Carnavalet.jpg','Public domain',1),
(12,'sao-jeronimo','São Jerônimo','Doutores da Igreja','Estudioso das Escrituras que dedicou grande parte da vida à tradução, estudo e transmissão da Palavra de Deus.',NULL,'Conhecer melhor a Escritura ajuda a conhecer melhor Cristo e a história da fé.','/assets/crismaquest/saints/sao-jeronimo-user.jpg?v=20260911f','Uso autorizado no CrismaQuest pelo administrador',1),
(13,'santo-inacio-antioquia','Santo Inácio de Antioquia','Mártires','Bispo dos primeiros séculos do cristianismo, deixou cartas importantes sobre unidade, Eucaristia e fidelidade a Cristo.',NULL,'A fé é vivida em comunhão: ninguém percorre sozinho o caminho cristão.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Ignatius_of_Antioch_2.jpg','Public domain',1),
(14,'santa-joana-darc','Santa Joana d’Arc','Santos Jovens','Jovem francesa cuja vida ficou marcada por coragem, discernimento, convicção e fidelidade à consciência diante de grandes desafios.',NULL,'Coragem cristã precisa caminhar com discernimento, responsabilidade e consciência bem formada.','https://commons.wikimedia.org/wiki/Special:Redirect/file/John_Everett_Millais_-_Joan_of_Arc.jpg','Public domain',1),
(15,'sao-john-henry-newman','São John Henry Newman','Doutores da Igreja','Intelectual, pastor e convertido inglês conhecido pela busca paciente da verdade e pelo valor dado à consciência bem formada.',NULL,'Fé e razão não precisam competir: ambas podem participar de uma busca honesta pela verdade.','https://commons.wikimedia.org/wiki/Special:Redirect/file/John_Henry_Newman_1887_Portrait_Photograph.jpg','Public domain',1),
(16,'sao-bento','São Bento','Fundadores','Monge cuja regra organizou uma vida equilibrada de oração, trabalho, comunidade e disciplina.',NULL,'Constância nasce de um ritmo de vida que integra oração, deveres e comunidade.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Pietro%20Perugino%20-%20Saint%20Benedict%20-%20WGA17310.jpg','Domínio público (PD-old-100-expired / PD-Art)',1),
(17,'santos-luis-e-zelia-martin','Santos Luís e Zélia Martin','Pais e Mães Santos','Casal francês e pais de Santa Teresinha, lembrados por viver a fé na família, no trabalho e nas alegrias e dificuldades cotidianas.',NULL,'A vida familiar pode ser lugar concreto de serviço, perdão, cuidado e crescimento na fé.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Collagelouiszeliemartin.jpg','Public domain',1),
(18,'sao-giuseppe-moscati','São Giuseppe Moscati','Santos Leigos','Médico italiano conhecido por unir competência profissional, atenção aos doentes e vida cristã.',NULL,'Conhecimento e profissão podem ser colocados a serviço da dignidade e do cuidado com o outro.','https://commons.wikimedia.org/wiki/Special:Redirect/file/San_Giuseppe_Moscati.jpg','CC BY-SA 3.0',1),
(19,'sao-pio-pietrelcina','São Pio de Pietrelcina','Presbíteros','Frade capuchinho cuja vida foi fortemente associada à oração, ao sacramento da Reconciliação e ao acompanhamento espiritual.',NULL,'Oração, conversão e reconciliação fazem parte de uma caminhada cristã que sempre pode recomeçar.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Padre_Pio_portrait.jpg','Public domain',1),
(20,'sao-sebastiao','São Sebastião','Mártires','Cristão dos primeiros séculos venerado como mártir, tradicionalmente associado à firmeza da fé diante da perseguição.',NULL,'Testemunhar a fé exige coerência e perseverança, inclusive quando isso custa alguma coisa.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Saint_Sebastian_painting.jpg','CC BY-SA 4.0',1),
(21,'sao-paulo','São Paulo','Apóstolos','Apóstolo e missionário, anunciou Jesus Cristo a diferentes povos e escreveu cartas que fazem parte do Novo Testamento.',NULL,'A fé se comunica com coragem e amor.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Saint%20Paul%20at%20his%20Writing-Desk%2C%20by%20Rembrandt.jpg','Domínio público (PD-old-100-expired / PD-Art)',1),
(22,'santa-clara-assis','Santa Clara de Assis','Fundadores','Companheira espiritual de São Francisco, dedicou sua vida à oração, à simplicidade e à comunidade.',NULL,'A simplicidade abre espaço para o essencial.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Santa_Chiara_d''Assisi_di_Giovan_Battista_Moroni.jpg','CC BY-SA 4.0',1),
(23,'santa-catarina-sena','Santa Catarina de Sena','Doutores da Igreja','Leiga dominicana, uniu a oração ao cuidado das pessoas e ao serviço à Igreja.',NULL,'O amor se torna concreto no cuidado com o próximo.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Catherine_of_Siena.jpg','Public domain',1),
(24,'sao-joao-bosco','São João Bosco','Fundadores','Sacerdote e educador italiano, dedicou-se à formação e ao acolhimento dos jovens.',NULL,'Educar é acompanhar com presença e esperança.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Portrait_de_Don_Bosco.jpg','Public domain',1),
(25,'santa-teresa-calcuta','Santa Teresa de Calcutá','Missionários','Fundou as Missionárias da Caridade e dedicou-se ao cuidado de pessoas pobres e abandonadas.',NULL,'Reconhecer a dignidade de cada pessoa é um chamado diário.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Mother_Teresa.jpg','CC BY 2.5',1),
(26,'santo-antonio-padua','Santo Antônio de Pádua','Doutores da Igreja','Frade franciscano nascido em Lisboa, conhecido pela pregação e pelo ensino das Escrituras.',NULL,'Conhecer a Palavra ajuda a servir melhor.','https://commons.wikimedia.org/wiki/Special:Redirect/file/San%20Antonio%20de%20Padua%20con%20Ni%C3%B1o%20(Murillo).jpg','Domínio público (PD-old-100-expired / PD-Art)',1),
(27,'sao-domingos-savio','São Domingos Sávio','Santos Jovens','Jovem aluno de Dom Bosco, viveu a fé na amizade, nos estudos e nos gestos cotidianos.',NULL,'Alegria e responsabilidade podem caminhar juntas.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Life_of_Dominic_Savio_(page_6_crop).jpg','Public domain',1),
(28,'sao-pier-giorgio-frassati','São Pier Giorgio Frassati','Santos Jovens','Jovem italiano que integrou a amizade, a vida de oração e o serviço aos pobres.',NULL,'A amizade com Cristo nos aproxima de quem precisa.','https://commons.wikimedia.org/wiki/Special:Redirect/file/PIER_GIORGIO_FRASSATI1925.jpg','Public domain',1),
(29,'sao-joao-evangelista','São João Evangelista','Apóstolos','Apóstolo de Jesus, ligado à tradição do quarto Evangelho e ao testemunho do amor cristão.',NULL,'Amar é permanecer próximo e cuidar.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Saint%20John%20the%20Evangelist%20by%20Carlo%20Dolce.jpg','Domínio público (PD-old-100-expired / PD-Art)',1),
(30,'santo-andre','Santo André','Apóstolos','Irmão de Pedro e um dos primeiros discípulos chamados por Jesus.',NULL,'Partilhar um encontro de fé pode abrir novos caminhos.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Van%20Dyck%20-%20Andrew%2C%2059.0093.jpg','Domínio público (PD-old-100-expired / PD-Art)',1),
(31,'sao-jose-anchieta','São José de Anchieta','Missionários','Jesuíta que viveu no Brasil e atuou como missionário, educador e escritor.',NULL,'Escutar e aprender também fazem parte da missão.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Benedito_Calixto_-_Retrato_do_Padre_Jos%C3%A9_de_Anchieta.jpg','Public domain',1),
(32,'santa-dulce-pobres','Santa Dulce dos Pobres','Missionários','Religiosa brasileira que dedicou sua vida ao acolhimento e ao cuidado de pessoas pobres e doentes na Bahia.',NULL,'A caridade encontra uma forma concreta de ajudar.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Irma-dulce-santa-canonizada.jpg','CC BY-SA 4.0',1),
(33,'santa-paulina','Santa Paulina','Fundadores','Religiosa que viveu no Brasil e fundou as Irmãzinhas da Imaculada Conceição, voltadas ao serviço e ao cuidado.',NULL,'Servir com perseverança transforma o cotidiano.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Santa_Paolina.jpg','CC BY-SA 2.5',1),
(34,'sao-frei-galvao','São Frei Galvão','Presbíteros','Frade franciscano brasileiro, lembrado pela oração, pelo acolhimento e pela dedicação à vida religiosa.',NULL,'A paz cresce em gestos de escuta e acolhida.','https://commons.wikimedia.org/wiki/Special:Redirect/file/An%C3%B4nimo_-_Frei_Galv%C3%A3o.jpg','Public domain',1),
(35,'santa-rita-cassia','Santa Rita de Cássia','Místicos','Esposa, mãe e depois religiosa agostiniana, lembrada pela oração e pela busca da reconciliação.',NULL,'A esperança pode acompanhar os recomeços.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Santa%20Rita%20de%20Casia%2C%20Miguel%20Cabrera.jpg','Domínio público (PD-old-100-expired / PD-Art)',1),
(36,'santa-teresa-avila','Santa Teresa d’Ávila','Doutores da Igreja','Carmelita e escritora espanhola, dedicou-se à oração e à renovação da vida de sua comunidade.',NULL,'A oração é um caminho de amizade com Deus.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Peter%20Paul%20Rubens%20-%20Hl.%20Therese%20von%20Avila%20-%20GG%207119%20-%20Kunsthistorisches%20Museum.jpg','Domínio público (PD-old-100-expired / PD-Art)',1),
(37,'sao-maximiliano-kolbe','São Maximiliano Kolbe','Mártires','Frade franciscano polonês que entregou sua vida no lugar de outro prisioneiro em Auschwitz.',NULL,'O amor reconhece o valor da vida do outro.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Fr.Maximilian_Kolbe_in_1936.jpg','Public domain',1),
(38,'santa-teresa-benedita-cruz','Santa Teresa Benedita da Cruz','Mártires','Edith Stein foi filósofa e carmelita. Foi assassinada em Auschwitz durante a perseguição nazista.',NULL,'Buscar a verdade pede coragem e respeito pela dignidade humana.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Edith_Stein_(ca._1938-1939).jpg','Public domain',1),
(39,'sao-martinho-porres','São Martinho de Porres','Santos Leigos','Irmão dominicano peruano, dedicou-se ao cuidado dos doentes e ao serviço dos pobres.',NULL,'Toda pessoa merece cuidado e respeito.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Martin%20de%20Porres.jpg','Domínio público (PD-old-100-expired / PD-Art)',1),
(40,'santa-josefina-bakhita','Santa Josefina Bakhita','Testemunhas da Esperança','Nascida no Sudão, sobreviveu à escravidão e tornou-se religiosa na Itália. Seu testemunho recorda a liberdade e a dignidade de cada pessoa.',NULL,'A dignidade humana não depende de origem ou condição.','https://commons.wikimedia.org/wiki/Special:Redirect/file/Photo_-_Portrait_der_Josefine_Bakhita.jpg','Public domain',1)
ON DUPLICATE KEY UPDATE
  slug=VALUES(slug),
  name=VALUES(name),
  category=VALUES(category),
  short_bio=VALUES(short_bio),
  feast_date=VALUES(feast_date),
  short_teaching=VALUES(short_teaching),
  image_path=VALUES(image_path),
  image_license=VALUES(image_license),
  active=1;

INSERT INTO cq_card_editions (card_id, edition_type, visual_asset, chance_weight, active)
SELECT id, 'normal', NULL, 100, 1
FROM cq_saint_cards
WHERE card_number BETWEEN 1 AND 40
ON DUPLICATE KEY UPDATE chance_weight=100, active=1;
