<?php $h=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8'); ?>
<div class="container-fluid py-3">
  <div class="cq-teacher-hero mb-3">
    <div><div class="cq-kicker">Supervisão</div><h1>Correio da Jornada</h1><p>Histórico da comunidade da turma. Nenhuma mensagem é anônima.</p></div>
    <a href="/docenti/dashboard" class="btn btn-light btn-sm">Voltar ao painel</a>
  </div>
  <div class="card mb-3"><div class="card-body"><h2 class="h5">Bilhetes recentes</h2><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Quando</th><th>De</th><th>Para</th><th>Mensagem</th></tr></thead><tbody><?php foreach(($notes??[]) as $n): ?><tr><td><?= $h($n['created_at']) ?></td><td><?= $h($n['sender_name']) ?></td><td><?= $h($n['recipient_name']) ?></td><td><?= $h($n['message_key']) ?><?= !empty($n['custom_text'])?' — “'.$h($n['custom_text']).'”':'' ?></td></tr><?php endforeach; ?><?php if(($notes??[])===[]): ?><tr><td colspan="4">Nenhum bilhete.</td></tr><?php endif; ?></tbody></table></div></div></div>
  <div class="card mb-3"><div class="card-body"><h2 class="h5">Presentes recentes</h2><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Quando</th><th>De</th><th>Para</th><th>Presente</th><th>Lúmens</th></tr></thead><tbody><?php foreach(($gifts??[]) as $g): ?><tr><td><?= $h($g['created_at']) ?></td><td><?= $h($g['sender_name']) ?></td><td><?= $h($g['recipient_name']) ?></td><td><?= $h($g['gift_name'] ?: ('Carta: '.$g['card_name'])) ?></td><td><?= (int)$g['cost_lumens'] ?></td></tr><?php endforeach; ?><?php if(($gifts??[])===[]): ?><tr><td colspan="5">Nenhum presente.</td></tr><?php endif; ?></tbody></table></div></div></div>
  <div class="card"><div class="card-body"><h2 class="h5">Trocas</h2><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Quando</th><th>Proponente</th><th>Destinatário</th><th>Troca</th><th>Status</th></tr></thead><tbody><?php foreach(($trades??[]) as $t): ?><tr><td><?= $h($t['created_at']) ?></td><td><?= $h($t['offerer_name']) ?></td><td><?= $h($t['recipient_name']) ?></td><td><?= $h($t['offered_name']) ?> ⇄ <?= $h($t['requested_name']) ?></td><td><?= $h($t['status']) ?></td></tr><?php endforeach; ?><?php if(($trades??[])===[]): ?><tr><td colspan="5">Nenhuma troca.</td></tr><?php endif; ?></tbody></table></div></div></div>
</div>
